defaults: &defaults
    hostname: "localhost"
    port: 3036

development:
    # add stuff here to override defaults.
    <<: *defaults

test:
    <<: *defaults

production:
    # add stuff here to override defaults.
    <<: *defaults
    port: 80
    hostname: 'short.en'
